export const cards = [
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '543021',
        name: 'Biryani By Kilo',
        uuid: '970f046b-8d3e-4703-99cf-3cb1eb04b356',
        city: '99',
        area: 'Dhanbad',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'fa5kyjxnxbbf7msdyutl',
        cuisines: [
          'Biryani',
          'Hyderabadi',
          'North Indian',
          'Kebabs',
          'Mughlai',
          'Desserts',
        ],
        tags: [],
        costForTwo: 70000,
        costForTwoString: '₹700 FOR TWO',
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: '49 MINS',
        lastMileTravel: 7,
        slugs: {
          restaurant: 'biryani-by-kilo-dhanbad-saraidhella',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'GROUND FLOOR,SHOP NO-2,3,5,6&7,NEWTECH GRAND 3, Dhanbad (Dhanbad Sadar), Dhanbad, Jharkhand-828127',
        locality: 'Dhanbad',
        parentId: 130,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '60% off',
          shortDescriptionList: [
            {
              meta: '60% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '60% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [{ type: 'PROMOTED' }],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5987615~p=1~eid=00000186-7373-33f1-1ce7-65a9008b0119',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '7 kms',
        hasSurge: false,
        sla: {
          restaurantId: '543021',
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 7,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.0',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '108186',
        name: 'Royal Biryani',
        uuid: '11a812af-c523-4df1-96fa-a643fa5ad76c',
        city: '99',
        area: 'Rangatand',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'hwxvfm07wjezvhuoeaul',
        cuisines: ['Biryani'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 15,
        minDeliveryTime: 15,
        maxDeliveryTime: 15,
        slaString: '15 MINS',
        lastMileTravel: 0.6000000238418579,
        slugs: {
          restaurant:
            'royal-biryani-sardarpatel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address: 'SHOP NO. 88, STATION ROAD, DHANBAD',
        locality: 'sardarpatel nagar',
        parentId: 13113,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '0.6 kms',
        hasSurge: false,
        sla: {
          restaurantId: '108186',
          deliveryTime: 15,
          minDeliveryTime: 15,
          maxDeliveryTime: 15,
          lastMileTravel: 0.6000000238418579,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.6',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '93070',
        name: 'Apple Restaurant',
        uuid: 'fde50a31-1a10-41c2-a429-3e53cbc70188',
        city: '99',
        area: 'Kasturba Nagar',
        totalRatingsString: '5000+ ratings',
        cloudinaryImageId: 'q3ninryemhdwba8eam8a',
        cuisines: ['Indian', 'Chinese', 'Tandoor', 'Biryani'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 21,
        minDeliveryTime: 21,
        maxDeliveryTime: 21,
        slaString: '21 MINS',
        lastMileTravel: 1.100000023841858,
        slugs: {
          restaurant:
            'apple-restaurant-sardar-patel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'Bekar Bandh Road, Near Dhanbad Railways Station, Kasturba Nagar, Dhanbad, Jharkhand 826001, India',
        locality: 'Sardar Patel Nagar',
        parentId: 35154,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '60% off',
          shortDescriptionList: [
            {
              meta: '60% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '60% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.1 kms',
        hasSurge: false,
        sla: {
          restaurantId: '93070',
          deliveryTime: 21,
          minDeliveryTime: 21,
          maxDeliveryTime: 21,
          lastMileTravel: 1.100000023841858,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.7',
        totalRatings: 5000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '553793',
        name: 'Goila Butter Chicken',
        uuid: '8a88b676-0471-4124-a625-3228295c65c4',
        city: '99',
        area: 'Dhanbad Sadar',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: '8047952208912b376eb800db0f9a45d0',
        cuisines: ['North Indian', 'Mughlai', 'Biryani', 'Indian'],
        tags: [],
        costForTwo: 60000,
        costForTwoString: '₹600 FOR TWO',
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: '49 MINS',
        lastMileTravel: 7,
        slugs: {
          restaurant: 'goila-butter-chicken-dhanbad-saraidhella',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'GROUND FLOOR,SHOP NO-2,3,5,6&7,NEWTECH GRAND 3, Dhanbad (Dhanbad Sadar), Dhanbad, Jharkhand-828127',
        locality: 'Dhanbad',
        parentId: 322587,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [{ type: 'PROMOTED' }],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5848967~p=4~eid=00000186-7373-33f1-1ce7-65aa008b041a',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '7 kms',
        hasSurge: false,
        sla: {
          restaurantId: '553793',
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 7,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '4.1',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '94249',
        name: 'Shahi Darbar - ISM ',
        uuid: 'd6e49a2f-63cb-405c-989b-780fa0729f18',
        city: '99',
        area: 'Ism Gate, Saraidhela Rd',
        totalRatingsString: '10000+ ratings',
        cloudinaryImageId: 'wxua0sgylfmfkg4h1alg',
        cuisines: ['Biryani', 'North Indian'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 24,
        minDeliveryTime: 24,
        maxDeliveryTime: 24,
        slaString: '24 MINS',
        lastMileTravel: 2.5999999046325684,
        slugs: {
          restaurant: 'shahi-darbar-saraidhella-saraidhella',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'Mini Market, I.S.M Road, Sardar Patel Nagar, Dhanbad, Jharkhand 826001, India',
        locality: 'Saraidhella',
        parentId: 180676,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '20% off',
          shortDescriptionList: [
            {
              meta: '20% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '20% off up to ₹50 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '20% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '20% off up to ₹50 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '94249',
          deliveryTime: 24,
          minDeliveryTime: 24,
          maxDeliveryTime: 24,
          lastMileTravel: 2.5999999046325684,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.6',
        totalRatings: 10000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '474296',
        name: 'BHARAT HINDU HOTEL Shop No. 26',
        uuid: 'd255f5cf-2dd6-4254-a05e-abf096c91c44',
        city: '99',
        area: 'Station Road',
        totalRatingsString: '500+ ratings',
        cloudinaryImageId: 'eaxwianbl4x9urg1sgc8',
        cuisines: ['North Indian', 'Biryani', 'Seafood', 'Chinese'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 19,
        minDeliveryTime: 19,
        maxDeliveryTime: 19,
        slaString: '19 MINS',
        lastMileTravel: 0.5,
        slugs: {
          restaurant:
            'bharat-hindu-hotel-shop-no.-26-sardar-patel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'Rly. Station Road Market Complex, Shop  No.26, P.O. & P.S.-Dhanbad, Dhanbad Urban,  Dhanbad, Jharkhand-826001',
        locality: 'Sardar Patel Nagar',
        parentId: 284910,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '45% off',
          shortDescriptionList: [
            {
              meta: '45% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '45% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '45% OFF',
          shortDescriptionList: [
            {
              meta: 'Free Delivery',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '45% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '0.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '474296',
          deliveryTime: 19,
          minDeliveryTime: 19,
          maxDeliveryTime: 19,
          lastMileTravel: 0.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.4',
        totalRatings: 500,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '528085',
        name: 'KWALITY HOTEL',
        uuid: '21affb15-7b38-4ad6-8bfc-83e565706954',
        city: '99',
        area: 'BankMore',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'ujhqbk5fw5tk0kq42gri',
        cuisines: ['Indian', 'Biryani'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 23,
        minDeliveryTime: 23,
        maxDeliveryTime: 23,
        slaString: '23 MINS',
        lastMileTravel: 1.899999976158142,
        slugs: {
          restaurant: 'kwality-hotel-bank-more-bank-more-2',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'Bank Road, Near DAV School, Dhanbad,  Dhanbad Urban, Dhanbad, Jharkhand-826001',
        locality: 'Bank More',
        parentId: 122208,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '60% off',
          shortDescriptionList: [
            {
              meta: '60% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '60% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [{ type: 'PROMOTED' }],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5803382~p=7~eid=00000186-7373-33f1-1ce7-65ab008b0721',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.8 kms',
        hasSurge: false,
        sla: {
          restaurantId: '528085',
          deliveryTime: 23,
          minDeliveryTime: 23,
          maxDeliveryTime: 23,
          lastMileTravel: 1.899999976158142,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '3.7',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '93885',
        name: 'Aroti Restaurant',
        uuid: 'f7a1c440-ede0-4e16-8a6f-6d6f062b7afe',
        city: '99',
        area: 'Sardar Patel Nagar',
        totalRatingsString: '10000+ ratings',
        cloudinaryImageId: 'xg8wswywwedan7ebmavf',
        cuisines: ['Indian', 'Chinese'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 26,
        minDeliveryTime: 26,
        maxDeliveryTime: 26,
        slaString: '26 MINS',
        lastMileTravel: 1.2999999523162842,
        slugs: {
          restaurant: 'aroti-restaurant-hirapur-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          '1st, Hira Palace, Hatia road, Hirapur, Park market, Dhanbad, Jharkhand 826001, India',
        locality: 'Sardar Patel Nagar',
        parentId: 36261,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '30% off',
          shortDescriptionList: [
            {
              meta: '30% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '30% off up to ₹75 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '30% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '30% off up to ₹75 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.2 kms',
        hasSurge: false,
        sla: {
          restaurantId: '93885',
          deliveryTime: 26,
          minDeliveryTime: 26,
          maxDeliveryTime: 26,
          lastMileTravel: 1.2999999523162842,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.0',
        totalRatings: 10000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '400837',
        name: 'Kohinoor Darbar',
        uuid: 'd053d26f-a306-41d6-8a19-83e24653c226',
        city: '99',
        area: 'Bank More',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'juppjcjhavapysv0wsfu',
        cuisines: ['Indian', 'Chinese'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 22,
        minDeliveryTime: 22,
        maxDeliveryTime: 22,
        slaString: '22 MINS',
        lastMileTravel: 1.5,
        slugs: {
          restaurant: 'kohinoor-darbar-bank-more-bank-more',
          city: 'dhanbad',
        },
        cityState: '99',
        address: 'Naya Bazar, Bhuli More, Dhanbad,',
        locality: 'Bank More',
        parentId: 119625,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '60% off',
          shortDescriptionList: [
            {
              meta: '60% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '60% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '400837',
          deliveryTime: 22,
          minDeliveryTime: 22,
          maxDeliveryTime: 22,
          lastMileTravel: 1.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.6',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '300308',
        name: "Kaveri's Restaurant",
        uuid: '4eb72d3b-dceb-4caf-a8be-89f40a58aed2',
        city: '99',
        area: 'Bank More',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'hawe8breczghxnwwwmwa',
        cuisines: [
          'North Indian',
          'Indian',
          'Chinese',
          'Biryani',
          'Kebabs',
          'Snacks',
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: '29 MINS',
        lastMileTravel: 2.5,
        slugs: {
          restaurant: 'kaveri’s-restaurant-bank-more-bank-more',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'RAJHANS MANTION, BANK MORE, P.S BANK  MORE DHANBAD (JHARKHAND) - 826001]',
        locality: 'Bank More',
        parentId: 115850,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '50% off',
          shortDescriptionList: [
            {
              meta: '50% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '50% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '50% off up to ₹100 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [{ type: 'PROMOTED' }],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5802809~p=10~eid=00000186-7373-33f1-1ce7-65ac008b0a28',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '300308',
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 2.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '3.9',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '384970',
        name: 'Wajid Hotel',
        uuid: 'c63bac01-fe5d-4277-8704-25fa15f583da',
        city: '99',
        area: 'Sardar Patel Nagar',
        totalRatingsString: '50+ ratings',
        cloudinaryImageId: 'k4tybijyp73e60jjoepn',
        cuisines: ['Indian'],
        tags: [],
        costForTwo: 15000,
        costForTwoString: '₹150 FOR TWO',
        deliveryTime: 20,
        minDeliveryTime: 20,
        maxDeliveryTime: 20,
        slaString: '20 MINS',
        lastMileTravel: 0.5,
        slugs: {
          restaurant:
            'wajid-hotel-sardar-patel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'Railway Shopping Complex, Shop no 12, Near Railway Station, DHANBAD',
        locality: 'Sardar Patel Nagar',
        parentId: 259038,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '20% off',
          shortDescriptionList: [
            {
              meta: '20% off | Use SWIGGYIT',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '20% off up to ₹50 | Use code SWIGGYIT',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '20% OFF',
          shortDescriptionList: [
            {
              meta: 'Use SWIGGYIT',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '20% off up to ₹50 | Use code SWIGGYIT',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '0.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '384970',
          deliveryTime: 20,
          minDeliveryTime: 20,
          maxDeliveryTime: 20,
          lastMileTravel: 0.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.9',
        totalRatings: 50,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '167628',
        name: 'Biryani Street',
        uuid: '1d41ead0-9de7-4fae-b291-896babae4823',
        city: '99',
        area: 'Ism Gate, Saraidhela Rd',
        totalRatingsString: '5000+ ratings',
        cloudinaryImageId: 'dba7zbszc92aa9mtulur',
        cuisines: ['Biryani', 'Chinese', 'Indian'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 25,
        minDeliveryTime: 25,
        maxDeliveryTime: 25,
        slaString: '25 MINS',
        lastMileTravel: 2.9000000953674316,
        slugs: {
          restaurant: 'biryani-street-dhanbad-saraidhella',
          city: 'dhanbad',
        },
        cityState: '99',
        address: 'SARAIDHELA ROAD, NEAR ISM, DHANBAD',
        locality: 'Saraidhella',
        parentId: 14466,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '60% off',
          shortDescriptionList: [
            {
              meta: '60% off | Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '60% OFF',
          shortDescriptionList: [
            {
              meta: 'Use TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '60% off up to ₹120 | Use code TRYNEW',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '2.9 kms',
        hasSurge: false,
        sla: {
          restaurantId: '167628',
          deliveryTime: 25,
          minDeliveryTime: 25,
          maxDeliveryTime: 25,
          lastMileTravel: 2.9000000953674316,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.3',
        totalRatings: 5000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '574048',
        name: 'AL- Hind Biryani',
        uuid: '578069b9-3e51-4b47-8600-8e82b7820748',
        city: '99',
        area: 'Alinagar bhuli More',
        totalRatingsString: 'Too Few Ratings',
        cloudinaryImageId: 'abk7zbh9p3foqkvscavy',
        cuisines: ['Biryani', 'Fast Food', 'Indian'],
        tags: [],
        costForTwo: 10000,
        costForTwoString: '₹100 FOR TWO',
        deliveryTime: 30,
        minDeliveryTime: 30,
        maxDeliveryTime: 30,
        slaString: '30 MINS',
        lastMileTravel: 1.7999999523162842,
        slugs: {
          restaurant: 'al--hind-biryani-katras-katras',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          'ModernTyreBuilding, Alinagar,BhukiRoad,opp.Zumzum Mall,Dhanbad',
        locality: 'Katras',
        parentId: 344545,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: 'FREE DELIVERY',
          shortDescriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [
            {
              meta: 'Free Delivery',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        ribbon: [{ type: 'PROMOTED' }],
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID:
          'cid=5930145~p=13~eid=00000186-7373-33f1-1ce7-65ad008b0d23',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '1.7 kms',
        hasSurge: false,
        sla: {
          restaurantId: '574048',
          deliveryTime: 30,
          minDeliveryTime: 30,
          maxDeliveryTime: 30,
          lastMileTravel: 1.7999999523162842,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: true,
        avgRating: '--',
        totalRatings: 0,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '106881',
        name: 'Hotel Sher-E-Punjab (Station Road)',
        uuid: '1ab0639f-4e67-4765-bbb1-97e03e82416e',
        city: '99',
        area: 'Pandey Muhalla',
        totalRatingsString: '1000+ ratings',
        cloudinaryImageId: 'ca58i4cpskf4zbud0wbp',
        cuisines: ['Indian'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 17,
        minDeliveryTime: 17,
        maxDeliveryTime: 17,
        slaString: '17 MINS',
        lastMileTravel: 0.5,
        slugs: {
          restaurant:
            'hotel-sher-e-punjab-sardar-patel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address: 'NEAR BUS STAND, STATION ROAD',
        locality: 'Sardar Patel Nagar',
        parentId: 102203,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: 'FREE DELIVERY',
          shortDescriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '',
          shortDescriptionList: [
            {
              meta: 'Free Delivery',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '0.5 kms',
        hasSurge: false,
        sla: {
          restaurantId: '106881',
          deliveryTime: 17,
          minDeliveryTime: 17,
          maxDeliveryTime: 17,
          lastMileTravel: 0.5,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '3.5',
        totalRatings: 1000,
        new: false,
      },
      subtype: 'basic',
    },
    {
      type: 'restaurant',
      data: {
        type: 'F',
        id: '619875',
        name: 'Basant Misthan Bhandar',
        uuid: 'b75ff2cb-21e5-4c8d-bbc6-431c8050867a',
        city: '99',
        area: 'Sardar Patel Nagar',
        totalRatingsString: '100+ ratings',
        cloudinaryImageId: 'ye75yka7how9bvawwsig',
        cuisines: ['Sweets', 'Desserts', 'Snacks'],
        tags: [],
        costForTwo: 20000,
        costForTwoString: '₹200 FOR TWO',
        deliveryTime: 16,
        minDeliveryTime: 16,
        maxDeliveryTime: 16,
        slaString: '16 MINS',
        lastMileTravel: 0.699999988079071,
        slugs: {
          restaurant:
            'basant-misthan-bhandar-sardar-patel-nagar-sardar-patel-nagar',
          city: 'dhanbad',
        },
        cityState: '99',
        address:
          '0, Bekarbandh, Forest Colony, Dhanbad, Jharkhand 826001, India',
        locality: 'Forest Colony',
        parentId: 369299,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfo: {
          header: '40% off',
          shortDescriptionList: [
            {
              meta: '40% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '40% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        aggregatedDiscountInfoV2: {
          header: '40% OFF',
          shortDescriptionList: [
            {
              meta: 'Free Delivery',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
          ],
          descriptionList: [
            {
              meta: '40% off on all orders',
              discountType: 'Percentage',
              operationType: 'RESTAURANT',
            },
            {
              meta: 'FREE DELIVERY',
              discountType: 'FREE_DELIVERY',
              operationType: 'RESTAURANT',
            },
          ],
          subHeader: '',
          headerType: 0,
          superFreedel: '',
        },
        chain: [],
        feeDetails: {
          fees: [],
          totalFees: 0,
          message: '',
          title: '',
          amount: '',
          icon: '',
        },
        availability: {
          opened: true,
          nextOpenMessage: '',
          nextCloseMessage: '',
        },
        longDistanceEnabled: 0,
        rainMode: 'NONE',
        thirdPartyAddress: false,
        thirdPartyVendor: '',
        adTrackingID: '',
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: '0.6 kms',
        hasSurge: false,
        sla: {
          restaurantId: '619875',
          deliveryTime: 16,
          minDeliveryTime: 16,
          maxDeliveryTime: 16,
          lastMileTravel: 0.699999988079071,
          lastMileDistance: 0,
          serviceability: 'SERVICEABLE',
          rainMode: 'NONE',
          longDistance: 'NOT_LONG_DISTANCE',
          preferentialService: false,
          iconType: 'EMPTY',
        },
        promoted: false,
        avgRating: '4.3',
        totalRatings: 100,
        new: false,
      },
      subtype: 'basic',
    },
  ]